version: '3.8'
services:
  backend:
    build:
      context: ./backend
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - newsletter-net

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - newsletter-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - newsletter-net
networks:
  newsletter-net:
    driver: bridge 