version: "3.9"

services:
  backend:
    build:
      context: ./backend
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - newsletter-net

  frontend:
    build:
      context: ./newsletter-frontend
    volumes:
      - ./newsletter-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
      - PORT=5173
      - REACT_APP_API_URL=http://localhost:3001
    networks:
      - newsletter-net

  admin-panel:
    build:
      context: ./newsletter-admin-panel
    volumes:
      - ./newsletter-admin-panel:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    environment:
      - HOST=0.0.0.0
      - PORT=5174
      - REACT_APP_API_URL=http://localhost:3001
    networks:
      - newsletter-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - newsletter-net

networks:
  newsletter-net:
    driver: bridge
